function discovery(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',xb='03EDE317FEA23610D61057EBA8348B5B.cache.html',zb='923CFA8ACE307091D7A39E83BDE87005.cache.html',cc='<script defer="defer">discovery.onInjectionDone(\'discovery\')<\/script>',gc='<script id="',A='=',q='?',ub='A59ADBD54DC61E6E6BF0C35F4C4F5258.cache.html',tb='AC76529759917772D2D947BFCF3775B0.cache.html',vb='BA8D54DB1F19DDDC48AD7297D084F0EC.cache.html',C='Bad handler "',bc='DOMContentLoaded',wb='E6BA181EE62FCFF43474E67F4500F98F.cache.html',o='SCRIPT',Ab='Upload.css',fc='__gwt_marker_discovery',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',m='discovery',ec='end',mb='gecko',ob='gecko1_8',yb='gwt.hybrid',ac='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',Fb='head',rb='hosted.html?discovery',Eb='href',lb='ie6',kb='ie8',ab='iframe',t='img',bb="javascript:''",Bb='link',qb='loadExternalRefs',v='meta',eb='moduleRequested',dc='moduleStartup',jb='msie',w='name',gb='opera',db='position:absolute;width:0;height:0;border:none',Cb='rel',ib='safari',sb='selectingPermutation',x='startup',Db='stylesheet',pb='unknown',fb='user.agent',hb='webkit';var ic=window,k=document,hc=ic.__gwtStatsEvent?function(a){return ic.__gwtStatsEvent(a)}:null,Cc,sc,nc,mc=l,vc={},Fc=[],Bc=[],lc=[],yc,Ac;hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!ic.__gwt_stylesLoaded){ic.__gwt_stylesLoaded={}}if(!ic.__gwt_scriptsLoaded){ic.__gwt_scriptsLoaded={}}function rc(){var b=false;try{b=ic.external&&(ic.external.gwtOnLoad&&ic.location.search.indexOf(yb)==-1)}catch(a){}rc=function(){return b};return b}
function uc(){if(Cc&&sc){var c=k.getElementById(m);var b=c.contentWindow;if(rc()){b.__gwt_getProperty=function(a){return oc(a)}}discovery=null;b.gwtOnLoad(yc,m,mc);hc&&hc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:ec})}}
function pc(){var j,h=fc,i;k.write(gc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){mc=f(j.src)}if(mc==l){var e=k.getElementsByTagName(s);if(e.length>0){mc=e[e.length-1].href}else{mc=f(k.location.href)}}else if(mc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=mc+u;mc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function zc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}vc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{Ac=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{yc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function Ec(d,e){var a=lc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function oc(d){var e=Bc[d](),b=Fc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Ac){Ac(d,a,e)}throw null}
var qc;function tc(){if(!qc){qc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);hc&&hc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(mc+Dc)}}
Bc[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){if(document.documentMode>=8){return kb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return lb}}}}else if(d.indexOf(mb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ob}return mb}return pb};Fc[fb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};discovery.onScriptLoad=function(){if(qc){sc=true;uc()}};discovery.onInjectionDone=function(){Cc=true;hc&&hc({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:ec});uc()};pc();var Dc;if(rc()){if(ic.external.initModule&&ic.external.initModule(m)){ic.location.reload();return}Dc=rb}zc();hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:sb});if(!Dc){try{Ec([gb],tb);Ec([ib],ub);Ec([kb],vb);Ec([ob],wb);Ec([mb],xb);Ec([lb],zb);Dc=lc[oc(fb)]}catch(a){return}}var xc;function wc(){if(!nc){nc=true;if(!__gwt_stylesLoaded[Ab]){var a=k.createElement(Bb);__gwt_stylesLoaded[Ab]=a;a.setAttribute(Cb,Db);a.setAttribute(Eb,mc+Ab);k.getElementsByTagName(Fb)[0].appendChild(a)}if(!__gwt_stylesLoaded[ac]){var a=k.createElement(Bb);__gwt_stylesLoaded[ac]=a;a.setAttribute(Cb,Db);a.setAttribute(Eb,mc+ac);k.getElementsByTagName(Fb)[0].appendChild(a)}uc();if(k.removeEventListener){k.removeEventListener(bc,wc,false)}if(xc){clearInterval(xc)}}}
if(k.addEventListener){k.addEventListener(bc,function(){tc();wc()},false)}var xc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){tc();wc()}},50);hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:ec});hc&&hc({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:nb});k.write(cc)}
discovery();